# ===============================
# DATASOURCE (PostgreSQL)
# ===============================

spring.jpa.database=postgresql
spring.datasource.driver-class-name=org.postgresql.Driver

# URL de conexión
spring.datasource.url=jdbc:postgresql://localhost:5432/web
spring.datasource.username=postgres
spring.datasource.password=tangananica2

# ===============================
# JPA / HIBERNATE
# ===============================

# Generar esquema
spring.jpa.generate-ddl=true

# OJO: en postgres NO usar create-drop en prod
spring.jpa.hibernate.ddl-auto=create-drop
# alternativas: update | validate | none

# Dialecto
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# LOGGING
# ===============================

# Muestra las queries
logging.level.org.hibernate.SQL=DEBUG

# Muestra parámetros
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Formato bonito
spring.jpa.properties.hibernate.format_sql=true